### PR TITLE
impl TryFrom, Into for Symbol via gen_symbol_for

### PR DESCRIPTION
**Pull request by lorenzleutgeb**
Thanks for this nice crate.

Maybe I am missing something, but consider that some users might want to get a `u{16,32}` from a `SymbolU{16,32}`. Using `to_usize` is a bit fiddly in that case.

### CODE REVIEW

**Comment by Robbepop** [comment]
Thank you for the PR!

I think this API might in fact be useful for consumers of this library.
However, I think the method should be called something like `into_inner` and also the PR is missing documentation and tests for the newly introduced API.

Maybe an extension trait for the `Symbol` trait might be useful but I am not entirely sure about that.
The extension trait could look like this:
```rust
pub trait SymbolExt {
    type Inner;
    fn into_inner(self) -> Self::Inner;
}
```

**Comment by Robbepop** [comment]
> However, I guess I can always implement my own Symbol, working around all that...

Actually that is a significantly good point.
So in the vein of keeping the API of a library as small as possible and as big as needed is there anything that you cannot do by simply creating your very own symbol type?

**Comment by lorenzleutgeb** [comment]
> > However, I guess I can always implement my own Symbol, working around all that...
> 
> Actually that is a significantly good point. So in the vein of keeping the API of a library as small as possible and as big as needed is there anything that you cannot do by simply creating your very own symbol type?

I don't think so, no. But it requires the `try_from_usize`/`to_usize` mapping, i.e. both functions currently members of `trait Symbol`. If you remove any of them, I think I'll have a hard time with my use-case.

Now, if you decide that you don't want to add any new traits to `Symbol`, and let users like me implement their own `Symbol`, that's totally okay. But then let me suggest something:

I'd argue that having `try_from_usize` is (in spirit) no different from implementing `TryFrom<usize>` and having `to_usize` is (in spirit) no different from implementing `Into<usize>`.

Ergo, `trait Symbol` could look like this: 

```rs
pub trait Symbol: Copy + Eq + TryFrom<usize> + Into<usize> {}
```

But you don't want to change your API. So how about a blanket implementation?

```rs
impl<T> Symbol for T
where
    T: Copy + Eq + TryFrom<usize> + Into<usize>
{
    #[inline]
    fn try_from_usize(index: usize) -> Option<Self> {
        Self::try_from(index).ok()
    }

    #[inline]
    fn to_usize(self) -> usize {
        self.into()
    }
}
```

That way you'd also get `impl Symbol for usize` for free.

**Comment by Robbepop** [comment]
You are right that one could define the `Symbol` trait like what you proposed with the small downside of having to choose an actual `Error` type for the `TryFrom<usize>` implementation and I am and was aware about this.
However, I personally am not a huge fan of automatic implementations for bridge types such as symbol types.
For me it is a feature to be explicit about what types users of my library want to be symbols.

Therefore I'd suggest you to simply define your very own symbol type with an API that is suitable for your use case. Everyone will have a slightly different use case so a minimal API is the best we can do.

**Pull request closed without merging**
